version: '3.8'

services:
  # app:
  #   build:
  #     context: ..
  #     dockerfile: .devcontainer/Dockerfile
    # env_file:
    #     - .env

    # volumes:
    #   - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  # postgres:
  #   image: postgres:latest
  #   restart: unless-stopped
  #   hostname: ${POSTGRES_HOST}
  #   env_file:
  #       - .env
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data


    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  instant-ngp:
    image: instantngp:latest
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    stdin_open: true
    tty: true
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics
      DISPLAY: $DISPLAY
    volumes:
      - ../:/volume
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../..:/workspaces:cached
    working_dir: /volume
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    command: python3 ./src/app.py
    env_file:
        - ../.env
    ports:
      - 443:443
    depends_on:
      - redis

    restart: unless-stopped

  redis:
    image: redis:7.0.8-alpine
    command: redis-server
    ports:
      - 6379:6379
  worker:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile_worker
    depends_on:
        - redis
    command: rq worker --url redis://redis:6379
    links:
        - redis

# volumes:
#   postgres-data:
