import os,time
from dotenv import load_dotenv
load_dotenv()

HIGH_MARCHING_CUBES_RES=512 #1024 may cause out of memory
MEDIUM_MARCHING_CUBES_RES=512
LOW_MARCHING_CUBES_RES=256

HIGH_REMOVE_INNER_PCD_ITERS=10
MEDIUM_REMOVE_INNER_PCD_ITERS=10
LOW_REMOVE_INNER_PCD_ITERS=10

HIGH_POISSON_DEPTH=12
MEDIUM_POISSON_DEPTH=10
LOW_POISSON_DEPTH=8


LOW_GPU_MEMORY_THRESHOLD=16000 #MB
MEDIUM_GPU_MEMORY_THRESHOLD=18000 #MB
HIGH_GPU_MEMORY_THRESHOLD=18000 #MB
QUEUE_NAME='PURECHOO'
FAILED_JOBS_RETRY=1
PURECHOO_BACKEND_URL=os.getenv('PURECHOO_BACKEND_URL')
REDIS_HOST=os.getenv('REDIS_HOST')
REDIS_PORT=os.getenv('REDIS_PORT')
FLASK_PORT=os.getenv('FLASK_PORT')
IMAGE_WIDTH=1000
IMAGE_HEIGHT=1000
